# Day: 12 Error Handling

### It is a part of 30 days of javascript challenge by chai aur code

<br>

## Activity 1: Basic Error Handling with Try-Catch
- Writing a function that intentionally throws an error and use try-catch block to handle error. 
- Creating a function that divides two numbers, and throws an error if the denominator is zero and using try-catch block to handle this error.

## [Code of Activity 1](Task_1_and_2.js)

<br>

## Activity 2: Finally Block
- Writing a script that includes try catch block and finally block to observe the execution flow.

## [Code of Activity 2](Task_3.js)

<br>

## Activity 3: Custom Error Objects
- Creating a custom error class that extends the built-in Error class. Throw an instance of this custom error in a function. 
- Writing a function that validates user input and throws a custom error if the validation fails.

## [Code of Activity 3](Task_4_and_5.html)

<br>

## Activity 4: Error Handling in Promises
- Creating a promise that randomly resolves or rejects. 
- Using try-catch within an async function to handle errors from a promise that randomly resolves or rejects.

## [Code of Activity 4](Task_6_and_7.js)

<br>

## Activity 5: Graceful Error Handling in Fetch
- Using the fetch API to request data from an invalid URL and handle the error using .catch().
- Using the fetch API to request data from an invalid URL within an async function and handle the error using try-catch.

## [Code of Activity 5](Task_8_and_9.js)

<br>
<br>

## Challenged by [Chai aur Code](https://github.com/hiteshchoudhary)<br> <br>Completed by [Nehal Jain](https://github.com/thebraudalf)